# 03 Conditions, cycles and libraries

## Conditions - if, elif, else

Conditions allow us to make decisions in our code based on certain criteria.

### Comparison Operators

- `==` : equal to
- `!=` : not equal to
- `>` : greater than
- `<` : less than
- `>=` : greater than or equal to
- `<=` : less than or equal to

### Logical Operators

- `and` : both conditions must be true
- `or` : at least one condition must be true
- `not` : negates a condition

Let's see some examples:

In [ ]:
# Basic if statement
age = 18
if age >= 18:
    print("You are an adult")

You are an adult


In [ ]:
#if-else statement
temperature = 32
if temperature > 30:
    print("It's hot today")
else:
    print("It's not too hot")

#TODO: Change temperature to 32 and see what happens

It's hot today


In [ ]:
# if-elif-else statement
score = 85
if score >= 90 and score <= 100:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
else:
    grade = "F"
print(f"Your grade is {grade}")

Your grade is B


In [ ]:
# TODO: Write code to check if a number is positive, negative, or zero and print the result
# Hint: Use if, elif, else statements

number = -5

# Your code here
if number > 0:
  print(number, "is postive")
elif number < 0:
  print(number, "is negative")
else:
  print(number, "is zero")

# TODO: Write code to check the username and password. For username "admin" is password "123" and for username
# "guest" or "student" is password "789". Print "Access granted" if the username and password are correct

username = "admin"
password = "123"

# Your code here
if username == "admin" and password == "123":
  print("Access granted")
elif username == "guest" or username == "student" and password == "789":
  print("Access granted")
else:
  print("Access denied")


-5
-5 is negative
Access granted


## Loops - for and while

Loops allow us to repeat code multiple times.

### for loop

Use when you know how many times to iterate or want to iterate over a sequence.

In [ ]:
# Loop through a list
fruits = ["apple", "banana", "orange"]
for fruit in fruits:
    print(f"I like {fruit}")

# Loop using range()
for i in range(5):
    print(f"Count: {i}")

# TODO: Print numbers 1 to 10 using for loop
for i in range(1, 11):
  print(i)

I like apple
I like banana
I like orange
Count: 0
Count: 1
Count: 2
Count: 3
Count: 4
1
2
3
4
5
6
7
8
9
10


### while loop

Use when you want to repeat while a condition is true.

In [ ]:
# Simple while loop
count = 0
while count < 5:
    print(f"Count: {count}")
    count += 1  # This is the same as count = count + 1

# TODO: Calculate sum of numbers from 1 to 5 using while loop
sum_result = 0
i = 1

# Your code here
while i <= 5:
  sum_result += i
  i += 1
print(sum_result)

Count: 0
Count: 1
Count: 2
Count: 3
Count: 4
15


## Working with Files

Python allows us to read from and write to files.

### Opening and closing files

We can open files using the `open()` function and then close them with `close()`.

In [ ]:
# Writing to a file (manual close)
file = open('example.txt', 'w')
file.write('Hello, this is a test file!\n')
file.write('This is the second line.\n')
file.close()

# Reading from a file (manual close)
file = open('example.txt', 'r')
content = file.read()
print(content)
file.close()

Hello, this is a test file!
This is the second line.



### Using 'with' statement (recommended)

The `with` statement automatically closes files for us, even if an error occurs.

In [ ]:
# Writing with 'with' statement
with open('example2.txt', 'w') as file:
    file.write('Hello, this is written with the with statement!\n')
    file.write('This is the second line.\n')

# Reading with 'with' statement
with open('example2.txt', 'r') as file:
    content = file.read()
    print(content)

Hello, this is written with the with statement!
This is the second line.



### File operations

Create a program that:
1. Writes a list of names to a file
2. Reads the file and prints each name
3. Appends a new name to the file

In [ ]:
# TODO: Exercise - File operations
# Step 1: Write names to a file names.txt
names = ['Alice', 'Bob', 'Charlie', 'Diana']
with open('names.txt', 'w') as file:
  file.write('\n'.join(names))

# Step 2: Read and print names from the file
with open('names.txt', 'r') as file:
  content = file.read()
  print(content)

# Step 3: Append a new name to the file
new_name = 'Eve'
with open('names.txt', 'a') as file:
    file.write('\n' + new_name)

with open('names.txt', 'r') as file:
  content = file.read()
  print(content)

Alice
Bob
Charlie
Diana
Alice
Bob
Charlie
Diana
Eve


## Libraries

Libraries extend Python's functionality. They are collections of pre-written code that we can use in our programs.

### Importing libraries

We use `import` to include a library in our program. We can also use an alias (short name) with `as`.

In [ ]:
# Importing a library
import math

# Importing with an alias
import numpy as np

# Importing specific functions
from math import sqrt, pi

## NumPy

NumPy (Numerical Python) is a powerful library for working with arrays and mathematical operations.

### Arrays vs Lists

NumPy arrays are more efficient and support vectorized operations compared to Python lists.

In [ ]:
# Creating arrays
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

print(f"List: {my_list}")
print(f"Array: {my_array}")

# Operations on arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Element-wise operations
print(f"Addition: {arr1 + arr2}")
print(f"Multiplication: {arr1 * 2}")
print(f"Square root: {np.sqrt(arr1)}")

List: [1, 2, 3, 4, 5]
Array: [1 2 3 4 5]
Addition: [ 7  9 11 13 15]
Multiplication: [ 2  4  6  8 10]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


### Basic operations with NumPy arrays

In [ ]:
# Creating a 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(f"Matrix:\n{matrix}")

# Basic statistics
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#TODO: use np.mean(), np.std() and np.sum() on data and matrix. Does it work the same?
print(np.mean(data))
print(np.mean(matrix))

print(np.std(data))
print(np.std(matrix))

print(np.sum(data))
print(np.sum(matrix))



Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
5.0
2.581988897471611
2.581988897471611
45
45


In [ ]:
# Creating arrays with zeros
zeros_array = np.zeros(5)
zeros_matrix = np.zeros((2, 3))

print(zeros_array)
print(zeros_matrix)

# TODO: create matrix 10x10 with ones
ones_matrix = np.ones((10, 10))
print(ones_matrix)

### Working with NaN values

In [ ]:
# Creating arrays with NaN values
data_with_nan = np.array([1, 2, np.nan, 4, 5])

print(f"Data with NaN: {data_with_nan}")

# Checking for NaN values
print(f"NaN values: {np.isnan(data_with_nan)}")

# TODO: try np.mean() and np.nanmean() operations
#np.mean9(data_with_nan)
np.nanmean(data_with_nan)

Data with NaN: [ 1.  2. nan  4.  5.]
NaN values: [False False  True False False]


np.float64(3.0)

### Normalization

Normalization scales data to a standard range, often 0 to 1.

In [ ]:
# Normalization example
data = np.array([10, 20, 30, 40, 50])

# TODO: calculate Min-Max normalization: (x - np.min()) / (np.max() - np.min()) and print
norm = (data - np.min(data)) / (np.max(data) - np.min(data))
print(norm)

[0.   0.25 0.5  0.75 1.  ]


## Summary

Today we've learned about:

1. **Conditions** - if, elif, else statements with comparison and logical operators
2. **Loops** - for and while loops for repeating code
3. **Libraries** - how to import and use libraries like NumPy
4. **File operations** - reading from and writing to files using both manual and with statements
5. **NumPy** - arrays, basic operations, handling NaN values, and normalization

These concepts form the foundation for more advanced Python programming.